name = "cloud-mail"
account_id = "dfb771ccbe430a8a29dbdc0cd2afd439"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = "ed730418-b701-469b-bc87-437a33925138"

[[kv_namespaces]]
binding = "kv"
id = "6ecc5e6f780b47fa80d819e97d46dc7d"

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = ""		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
domain = ["kaka.locationindoor.cn"]	#邮件域名可配置多个 示例: ["example1.com","example2.com"]
admin = "admin@kaka.locationindoor.cn"	#管理员的邮箱
jwt_secret = "5e10cdad698de1f32fdb331e68b88cef04d2f980cbec123e49e6dc3c123818c7"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"

[[routes]]
pattern = "kaka.locationindoor.cn"
custom_domain = true
