name = "cloud-mail"
account_id = "0043a46c95bc18954ef875323b4ee22c"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "email"
database_id = "1e974942-f0b7-4ad4-aa84-457643436f8d"

[[kv_namespaces]]
binding = "kv"
id = "c4c78acfaddf4222bb564b81f2938969"

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = ""		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
domain = ["cili.llmailab.xyz"]	#邮件域名可配置多个 示例: ["example1.com","example2.com"]
admin = "admin@cili.llmailab.xyz"	#管理员的邮箱
jwt_secret = "5e10cdad698de1f32fdb331e68b88cef04d2f980cbec123e49e6dc3c123818c7"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"

[[routes]]
pattern = "cili.llmailab.xyz"
custom_domain = true
